default:
  image: docker
  services:
    - name: docker:dind
      command:
        - --tls=false
        - --registry-mirror=https://registry.ik8s.ir
        - --insecure-registry=registry.ik8s.ir
  before_script:
    - mkdir -p ~/.docker
    - |
      cat > ~/.docker/config.json <<EOF
      {
        "auths": {
          "registry.ik8s.ir": {
            "auth": "$(echo -n "malek:rizabadibayandor" | base64)"
          }
        }
      }
      EOF
variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

stages:
  - test
  - build
  - update

build-docker-image:
  stage: build
  script:
    - echo $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG .
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker image push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  only:
    - /^v[0-9]+(\.[0-9]+){0,2}(-rc\.[0-9]+)?$/
  tags:
    - gitops-runner

release-candidate-gitops:
  stage: update
  variables:
    GITOPS_CI_IMAGE_NAMESPACE: "$CI_PROJECT_NAMESPACE"
    GITOPS_CI_IMAGE_NAME: "$CI_PROJECT_NAME"
    GITOPS_CI_IMAGE_TAG: "$CI_COMMIT_TAG"
    GITOPS_CI_ZONE: "cdn"
    GITOPS_CI_TRIGGER: "true"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(?:\.[0-9]+)+-rc\.[0-9]+$/'
  trigger:
    project: novincloud/gitops
    branch: staging

production-gitops:
  stage: update
  variables:
    GITOPS_CI_IMAGE_NAMESPACE: "$CI_PROJECT_NAMESPACE"
    GITOPS_CI_IMAGE_NAME: "$CI_PROJECT_NAME"
    GITOPS_CI_IMAGE_TAG: "$CI_COMMIT_TAG"
    GITOPS_CI_ZONE: "cdn"
    GITOPS_CI_TRIGGER: "true"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+){0,2}$/'
  trigger:
    project: novincloud/gitops
    branch: main
